### ISSUE TITLE
[Question] two controller talking to each other

### ISSUE THREAD

**Issue by arminposchmann** [aptly-io/psga#12]
is it possible  that one controller asks another for its values? 
Controller 1 is a tree widget storing the last displayed path.
Controller 2 controls buttons requiring the information  last path. 
Is it possible to aquire this information via the dispatcher?

**Comment by aptly-io** [comment]
The Dispatcher is the event loop; picking up events and calling their associated call-back.

You could use `window.write_event_value()` from one controller which would then end up in another controller's action like this (clicking the button sends some text to another controller's action):
```python
import PySimpleGUI as sg
from psga import Controller, Dispatcher, action


class TreeController(Controller):
    @action()
    def on_selection_changed(self, values):
        print(f"values: {values}")


class ButtonController(Controller):
    @action()
    def on_ok(self, _):
        self.window.write_event_value(TreeController.on_selection_changed.name, "NEW SELECTION")


window = sg.Window("Window Title", [[ sg.Button("Ok", key=ButtonController.on_ok.name),],])

dispatcher = Dispatcher()
tree_controller = TreeController(dispatcher, window)
button_contoller = ButtonController(dispatcher, window)
dispatcher.loop(window)
window.close()
```

Another approach could use a parent controller, owning child-controllers (your tree widget and buttons container).
You would than store the temporary state, like a selection in the tree widget, in that parent controller.
Another sibling controller could query its parent for the temporary state.

Hope this answers your question!

**Comment by arminposchmann** [comment]
I tried with write_event_value already, but it has some bad side effects (timing of actions). I found another way already.
I am now storing all controllers inside the dispatcher class. so any controller can query all others by name. 
There may be other ways. I will try your suggestions. 
Closing this question as answered.
Thank you very much for your suggestions and for this project.
